### ISSUE TITLE
Forward reference issue with RefCounted

### ISSUE THREAD

**Issue by burner** [burner/bugzilla_migration_test#260]
### CC List

* bugzilla
* monarchdodra

### Description

Consider:

import std.typecons;

struct GroupBy(R)
{
    {
        Group unused;
    }

```dlang
    {
        private RefCounted!SharedInput _allGroups;
    }
}

```
{
    GroupBy!(int[]) g1;
}

#### bugzilla commented on 2014-01-25T20:48:39Z

Eliminating the dependency on Phobos:
--------------------------------------------
struct RefCounted(T)
{
    {
        {
            SharedInput _payload;
        }

        {
            import core.memory;
        }

```dlang
        {
            initialize();
        }

    }
    RefCountedStore _refCounted;

```
    {
    }

```dlang
    {
        _refCounted.ensureInitialized();
        return 0;
    }

    int refCountedPayload() inout;

    alias refCountedPayload this;
}

struct SharedInput
{
    Group unused;
}

struct Group
{
    RefCounted!SharedInput _allGroups;
}
```
foo.d(6): Error: struct foo.RefCounted!(SharedInput).RefCounted.RefCountedStore.Impl unable to resol
ve forward reference in definition
foo.d(46): Error: template instance foo.RefCounted!(SharedInput) error instantiating

#### bugzilla commented on 2014-01-25T21:08:42Z

Just noticed this compiles with 2.064, marking as regression

#### bugzilla commented on 2014-01-25T21:10:37Z

Actually, example 1 still fails with 2.064, while example 2 succeeds.

#### k.hara.pg commented on 2014-01-27T01:27:41Z

(In reply to comment #1)
> Eliminating the dependency on Phobos:
[snip]

I separated compiler regression into issue 12008.

(In reply to comment #0)
> Consider:
> 
> import std.typecons;
> struct GroupBy(R)
> {
>     {
>         Group unused;
>     }
>     struct Group
>     {
>         private RefCounted!SharedInput _allGroups;
>     }
> }
> unittest
> {
>     GroupBy!(int[]) g1;
> }
> This came about while I was working on #5968. The intent here is to have each
> group have a backreference to the mother hen of all groups. However, the code
> does not compile due to protests about forward reference issues (specifically
> not knowing the size). It should, seeing as RefCounted is just a pointer so the
> size is not needed to define Group's layout.

The root cause is in the implementation of RefCounted.

import std.traits : hasIndirections;

struct RefCounted(T)
{
```dlang
    {
        static if (hasIndirections!T) { /* ... */ }
    }
}

```

To fix the issue, following fix would be necessary.

struct RefCounted(T)
{
    {
        { /* ... */ }
    }
}

#### k.hara.pg commented on 2014-01-27T01:47:30Z

I found one more compiler issue.
Issue 12009 - local import and "unable to resolve forward reference" error

#### monarchdodra commented on 2014-04-05T04:24:32Z

See also:
http://forum.dlang.org/thread/wokatnixzkulvmfujamr@forum.dlang.org

Reduced to:
```dlang
//----
struct S(T) 
{
    static assert(hasIndirections!T);
}

class A(T) 
{
    S!A a;
}

A!int dummy;
//----

```

#### monarchdodra commented on 2014-04-05T04:39:34Z

https://github.com/D-Programming-Language/phobos/pull/2070

#### github-bugzilla commented on 2014-04-25T23:54:02Z

Commit pushed to master at https://github.com/D-Programming-Language/phobos

https://github.com/D-Programming-Language/phobos/commit/bc1876626bbefd54941154733f667012e290a4d3
Re-implement hasIndirections

Avoids requesting the RepresentationTypeTuple of T unless really needed.

Partially solves 12000:
https://d.puremagic.com/issues/show_bug.cgi?id=12000

Fix Issue 12000 - Forward reference issue with RefCounted
